"""PostgreSQL + pgvector 连接及表结构初始化。"""
from __future__ import annotations

import logging
import re
import threading
from contextlib import contextmanager
from typing import Iterator

from app.config import (
    PGVECTOR_EF_CONSTRUCTION,
    PGVECTOR_HNSW_M,
    POSTGRES_DSN,
    POSTGRES_SCHEMA,
    VECTOR_DIMENSION,
)

logger = logging.getLogger(__name__)
_database_initialized = False
_init_lock = threading.Lock()

if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", POSTGRES_SCHEMA):
    raise ValueError("POSTGRES_SCHEMA 只能包含字母、数字和下划线，且不能以数字开头")


def _table(name: str) -> str:
    """返回经过配置校验的限定表名。"""
    return f'"{POSTGRES_SCHEMA}"."{name}"'


@contextmanager
def get_connection(*, register_vectors: bool = True) -> Iterator:
    """提供事务连接；正常退出提交，异常退出回滚。"""
    import psycopg

    conn = psycopg.connect(POSTGRES_DSN)
    try:
        if register_vectors:
            from pgvector.psycopg import register_vector

            register_vector(conn)
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def init_database() -> None:
    """安装 vector 扩展并初始化业务表、向量表与 HNSW 索引。"""
    global _database_initialized
    if _database_initialized:
        return
    with _init_lock:
        if _database_initialized:
            return
        _init_database_once()
        _database_initialized = True


def _init_database_once() -> None:
    """执行一次实际的 DDL 初始化。"""
    import psycopg
    from pgvector.psycopg import register_vector

    patents = _table("patents")
    chunks = _table("patent_chunks")
    knowledge = _table("knowledge_documents")
    documents = _table("patent_documents")
    retrieval_runs = _table("retrieval_runs")
    retrieval_results = _table("retrieval_results")
    evaluation_results = _table("evaluation_results")

    with psycopg.connect(POSTGRES_DSN) as conn:
        with conn.cursor() as cur:
            cur.execute("CREATE EXTENSION IF NOT EXISTS vector")
            cur.execute(f'CREATE SCHEMA IF NOT EXISTS "{POSTGRES_SCHEMA}"')
        register_vector(conn)
        with conn.cursor() as cur:
            cur.execute(
                f"""
                CREATE TABLE IF NOT EXISTS {patents} (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    patent_number TEXT NOT NULL UNIQUE,
                    title TEXT NOT NULL DEFAULT '',
                    applicant TEXT NOT NULL DEFAULT '',
                    ipc_classification TEXT,
                    application_date TEXT,
                    publication_date TEXT,
                    abstract TEXT NOT NULL,
                    technical_field TEXT NOT NULL DEFAULT '',
                    metadata JSONB NOT NULL DEFAULT '{{}}'::jsonb,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                )
                """
            )
            cur.execute(
                f"""
                CREATE TABLE IF NOT EXISTS {chunks} (
                    id TEXT PRIMARY KEY,
                    patent_id BIGINT NOT NULL REFERENCES {patents}(id) ON DELETE CASCADE,
                    chunk_index INTEGER NOT NULL,
                    content TEXT NOT NULL,
                    embedding vector({VECTOR_DIMENSION}) NOT NULL,
                    metadata JSONB NOT NULL DEFAULT '{{}}'::jsonb,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    UNIQUE (patent_id, chunk_index)
                )
                """
            )
            cur.execute(
                f"""
                CREATE TABLE IF NOT EXISTS {knowledge} (
                    id TEXT PRIMARY KEY,
                    document_type TEXT NOT NULL CHECK (document_type IN ('template', 'rule')),
                    content TEXT NOT NULL,
                    embedding vector({VECTOR_DIMENSION}) NOT NULL,
                    metadata JSONB NOT NULL DEFAULT '{{}}'::jsonb,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                )
                """
            )
            cur.execute(
                f"""
                CREATE TABLE IF NOT EXISTS {documents} (
                    document_id TEXT PRIMARY KEY,
                    request_id TEXT NOT NULL,
                    user_id TEXT,
                    title TEXT NOT NULL,
                    abstract TEXT,
                    content TEXT NOT NULL,
                    risk_level TEXT NOT NULL DEFAULT 'low',
                    iteration_count INTEGER NOT NULL DEFAULT 0,
                    token_usage JSONB,
                    state_data JSONB,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                )
                """
            )
            cur.execute(
                f"""
                CREATE TABLE IF NOT EXISTS {retrieval_runs} (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    request_id TEXT,
                    query_text TEXT NOT NULL,
                    filters JSONB NOT NULL DEFAULT '{{}}'::jsonb,
                    latency_ms INTEGER,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                )
                """
            )
            cur.execute(
                f"""
                CREATE TABLE IF NOT EXISTS {retrieval_results} (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    retrieval_run_id BIGINT NOT NULL REFERENCES {retrieval_runs}(id) ON DELETE CASCADE,
                    patent_id BIGINT REFERENCES {patents}(id) ON DELETE SET NULL,
                    rank INTEGER NOT NULL,
                    vector_score DOUBLE PRECISION,
                    bm25_score DOUBLE PRECISION,
                    rerank_score DOUBLE PRECISION,
                    result_data JSONB NOT NULL DEFAULT '{{}}'::jsonb
                )
                """
            )
            cur.execute(
                f"""
                CREATE TABLE IF NOT EXISTS {evaluation_results} (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    retrieval_run_id BIGINT REFERENCES {retrieval_runs}(id) ON DELETE CASCADE,
                    metric_name TEXT NOT NULL,
                    metric_value DOUBLE PRECISION NOT NULL,
                    details JSONB NOT NULL DEFAULT '{{}}'::jsonb,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                )
                """
            )

            cur.execute(
                f"CREATE INDEX IF NOT EXISTS idx_patents_applicant ON {patents}(applicant)"
            )
            cur.execute(
                f"CREATE INDEX IF NOT EXISTS idx_patents_ipc ON {patents}(ipc_classification)"
            )
            cur.execute(
                f"CREATE INDEX IF NOT EXISTS idx_patents_publication_date ON {patents}(publication_date)"
            )
            cur.execute(
                f"CREATE INDEX IF NOT EXISTS idx_patent_chunks_patent_id ON {chunks}(patent_id)"
            )
            cur.execute(
                f"""CREATE INDEX IF NOT EXISTS idx_patent_chunks_embedding_hnsw
                ON {chunks} USING hnsw (embedding vector_cosine_ops)
                WITH (m = {PGVECTOR_HNSW_M}, ef_construction = {PGVECTOR_EF_CONSTRUCTION})"""
            )
            cur.execute(
                f"""CREATE INDEX IF NOT EXISTS idx_knowledge_embedding_hnsw
                ON {knowledge} USING hnsw (embedding vector_cosine_ops)
                WITH (m = {PGVECTOR_HNSW_M}, ef_construction = {PGVECTOR_EF_CONSTRUCTION})"""
            )
            cur.execute(
                f"CREATE INDEX IF NOT EXISTS idx_knowledge_type ON {knowledge}(document_type)"
            )
            cur.execute(
                f"CREATE INDEX IF NOT EXISTS idx_patent_documents_user_id ON {documents}(user_id)"
            )
            cur.execute(
                f"CREATE INDEX IF NOT EXISTS idx_patent_documents_created_at ON {documents}(created_at DESC)"
            )
            cur.execute(
                f"CREATE INDEX IF NOT EXISTS idx_retrieval_runs_created_at ON {retrieval_runs}(created_at DESC)"
            )
            cur.execute(
                f"CREATE INDEX IF NOT EXISTS idx_retrieval_results_run ON {retrieval_results}(retrieval_run_id, rank)"
            )
        conn.commit()
    logger.info("PostgreSQL/pgvector 表结构初始化完成，schema=%s", POSTGRES_SCHEMA)


def table_name(name: str) -> str:
    """供仓储层使用的限定表名。"""
    return _table(name)
